# Inserts a blank line between shell prompts
add_newline = false 

format = """
$username\
$hostname\
$singularity\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$memory_usage\
$cmd_duration\
$jobs\
$battery\
$time\
$status\
$shell\
$character"""

[character]
success_symbol = "[➜](bold green) "
error_symbol = "[✗](bold red) "
vicmd_symbol = "[V](bold green) "

[package]
disabled = false 

[[battery.display]]
threshold = 20
style = "bold red"

[directory]
truncation_symbol = ".../"

